### ISSUE TITLE
Get "self._drilldown is not a function" error after upgrading app to Meteor 1.5.1

### ISSUE THREAD

**Issue by rjsmith** [JackAdams/meteor-transactions#91]
Using babrahams:transactions version 0.8.4 in my application that I have just upgraded to Meteor 1.5.1

Stack trace:

> TypeError: self._drillDown is not a function\n    at collections/tx/txInverse.js:42:30\n    at Array.forEach (native)\n    at Function._.each._.forEach (packages/underscore.js:139:11)\n    at [object Object]._inverseSet (collections/tx/txInverse.js:41:9)\n    at [object Object].Transact.update (packages/babrahams_transactions.js:924:96)\n    at [object Object].self.(anonymous function) [as update] (packages/babrahams_transactions.js:364:31)\n    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/babrahams_transactions.js:1900:29)\n    at _beforeCommit (server/methods/requirementsMethods.js:2206:35)\n    at [object Object].Meteor.methods.plRequirementReplaceRequirementParameter (server/methods/requirementsMethods.js:1469:7)\n    at [object Object].methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2731:30)'

**Comment by rjsmith** [comment]
Whoops. Sorry. This is in my custom tx.inverse implementation. Not in the package code.
